### ISSUE TITLE
TAB not working ( probably clashing with EMMET's TAB)

### ISSUE THREAD

**Issue by lapak10** [justinblough/Atom-AngularJS-Boilerplate-Snippets#1]
recently i tried to type in angcon and then hit TAB ...but it did nothing unlike mentioned in the docs.

I have emmet plugin install which is quite common nowadays web dev use... so is there anyway toh shift that TAB key binding to someother key?

**Comment by justinblough** [comment]
@lapak10 It is also a similar issue with autocomplete plus and emmet. I like the suggestion of adding an additional binding which I will look to get integrated. in the meantime I incorporated this fix that works for situations with emmet and autocomplete plus as well.

Add the following in your `atom > keymap` file:

```
# Stop emmet from hijacking tab from snippets and autocomplete
'atom-text-editor.autocomplete-active:not([mini])':
  'tab': 'autocomplete-plus:confirm'

# Stop emmet from hijacking tab from snippet tab stops
'atom-text-editor[data-grammar="text html basic"]:not([mini]), atom-text-editor[data-grammar~="jade"]:not([mini]), atom-text-editor[data-grammar~="css"]:not([mini]), atom-text-editor[data-grammar~="sass"]:not([mini])':
  'tab': 'snippets:next-tab-stop'
```

**Comment by lapak10** [comment]
@justinblough Thanks mate!...Fixed!
